const CACHE='180-days-v8';
const ASSETS=['./manifest.json','./icon-192.png','./icon-512.png','./spider-theme.css','./runloop.html'];

self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim();});

const protectionScript=`<script>(()=>{const KEY='avance_lineal_6_meses_v1',BACKUP=KEY+'_safe_backup',DB='180DaysRecovery',STORE='backup';function openDB(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject();const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}async function dbWrite(value){try{const db=await openDB(),tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,'latest');tx.oncomplete=()=>db.close()}catch(e){}}async function dbRead(){try{const db=await openDB();return await new Promise(res=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get('latest');r.onsuccess=()=>{db.close();res(r.result||null)};r.onerror=()=>{db.close();res(null)}})}catch(e){return null}}function snapshot(){try{const v=localStorage.getItem(KEY);if(v){localStorage.setItem(BACKUP,v);dbWrite(v)}}catch(e){}}async function recover(){try{if(localStorage.getItem(KEY)){snapshot();return}let v=localStorage.getItem(BACKUP);if(!v)v=await dbRead();if(v){localStorage.setItem(KEY,v);location.reload()}}catch(e){}}if(navigator.storage&&navigator.storage.persist)navigator.storage.persist().catch(()=>{});recover();setInterval(snapshot,1500);addEventListener('pagehide',snapshot);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')snapshot()})})();<\/script>`;

const splashMarkup=`<section class="splash" id="splashScreen" aria-label="Pantalla de inicio"><div class="city-grid"></div><div class="web one"></div><div class="web two"></div><div class="splash-card"><div class="hero-badge">🕷️ Modo héroe activado</div><h1>6 MESES<br><span>DE PROGRESO</span></h1><p>Cada día cuenta. Completa tus objetivos, protege tu racha y desbloquea tus recompensas.</p><div class="splash-stats"><div class="splash-stat">🔥 Racha: <strong id="splashCurrentStreak">0 días</strong></div><div class="splash-stat">🏆 Mejor: <strong id="splashBestStreak">0 días</strong></div><div class="splash-stat">⚡ Progreso: <strong id="splashProgress">0%</strong></div></div><button class="enter-btn" id="enterAppButton">Entrar al calendario →</button></div></section>`;

const runloopLauncher=`<section id="runloop-launcher" style="margin:0 0 20px;padding:16px;border-radius:18px;border:1px solid rgba(255,255,255,.10);background:radial-gradient(circle at 100% 0%,rgba(47,125,246,.16),transparent 38%),radial-gradient(circle at 0 100%,rgba(239,35,60,.14),transparent 38%),linear-gradient(180deg,rgba(255,255,255,.035),rgba(255,255,255,.012)),#0b101a;box-shadow:0 18px 45px rgba(0,0,0,.32)"><div style="font-size:11px;font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:#ff6b79;margin-bottom:7px">🕷️ Spider Run</div><div style="font-size:20px;font-weight:900;margin-bottom:5px">Planifica tu recorrido</div><div style="font-size:13px;line-height:1.45;color:#93a4b8;margin-bottom:13px">Genera rutas peatonales con filtro para reducir callejones sin salida y retrocesos.</div><a href="runloop.html?v=4" style="display:inline-flex;text-decoration:none;color:white;font-weight:900;font-size:14px;padding:12px 16px;border-radius:13px;background:linear-gradient(135deg,#ef233c,#b80d28);box-shadow:0 12px 28px rgba(239,35,60,.28)">Abrir RunLoop →</a></section>`;

const splashScript=`<script>(()=>{function syncSplash(){const s=document.getElementById('stats'),c=document.getElementById('currentStreak'),b=document.getElementById('bestStreak'),sp=document.getElementById('splashProgress'),sc=document.getElementById('splashCurrentStreak'),sb=document.getElementById('splashBestStreak');if(s&&sp){const m=s.textContent.match(/(\\d+)%/);if(m)sp.textContent=m[1]+'%'}if(c&&sc)sc.textContent=c.textContent;if(b&&sb)sb.textContent=b.textContent}const btn=document.getElementById('enterAppButton');if(btn)btn.addEventListener('click',()=>{const splash=document.getElementById('splashScreen');if(splash)splash.classList.add('hidden');setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),120)});syncSplash();setTimeout(syncSplash,100);setTimeout(syncSplash,500)})();<\/script>`;

self.addEventListener('fetch',event=>{const req=event.request,url=new URL(req.url);const isMainHtml=req.mode==='navigate'&&(url.pathname.endsWith('/index.html')||url.pathname.endsWith('/180-days-/'));if(isMainHtml){event.respondWith((async()=>{try{const response=await fetch(req,{cache:'no-store'});let text=await response.text();if(!text.includes('spider-theme.css'))text=text.replace('</head>','<link rel="stylesheet" href="spider-theme.css?v=8">\n</head>');if(!text.includes('id="splashScreen"'))text=text.replace('<body>','<body>\n'+splashMarkup);if(!text.includes('id="runloop-launcher"'))text=text.replace('<div class="controls">',runloopLauncher+'\n<div class="controls">');if(!text.includes('180DaysRecovery'))text=text.replace('</body>',protectionScript+'\n</body>');if(!text.includes('syncSplash'))text=text.replace('</body>',splashScript+'\n</body>');return new Response(text,{status:response.status,statusText:response.statusText,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})}catch(e){const cached=await caches.match('./index.html');return cached||new Response('Sin conexión',{status:503})}})());return}if(url.pathname.endsWith('/runloop.html')){event.respondWith(fetch(req,{cache:'no-store'}).catch(()=>caches.match('./runloop.html')));return}event.respondWith(caches.match(req).then(cached=>cached||fetch(req).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(req,copy));return response})));});